### ISSUE TITLE
Magnify Glass Search Button Component

### ISSUE THREAD

**Issue by mrrogercampbell** [ZakkMan/modern-trousseau#4]
## Description
Magnify Glass Search Button Component should render a magnify glass icon.

This component should have a clickEvent that should render a `Search Bar Component`.

## Mock Example
![image](https://user-images.githubusercontent.com/43559077/71692471-f56ad980-2d77-11ea-8921-a524fc221a79.png)

**Comment by 0xZakk** [comment]
This should just be an `Icon` component
